use pokdex;

SELECT * FROM pokedex.tipo;

ALTER TABLE tipo -- alterar nome da coluna
CHANGE COLUMN FRAQUEZA_TIPO_TEXT0 FRAQUEZA_TIPO_TEXTO VARCHAR(45);

ALTER TABLE tipo -- alterar nome da coluna
CHANGE COLUMN RESISTENCIA_TIPO_TEXT0 RESISTENCIA_TIPO_TEXTO VARCHAR(45);

ALTER TABLE movimento -- alterar nome da coluna
CHANGE COLUMN ID_TIPO_MOVIEMNTO_TEXTO ID_TIPO_MOVIMENTO_TEXTO VARCHAR(45);

ALTER TABLE tipo -- alterar a quantidade ou tipo da coluna
MODIFY COLUMN RESISTENCIA_TIPO_TEXTO VARCHAR(100);


