USE Pokedex;
SELECT * FROM TIPO;
CREATE TABLE TIPO (
ID_TIPO INT PRIMARY KEY,
NOME_TIPO VARCHAR (45) DEFAULT  "-",
VANTAGEM_TIPO_TEXTO VARCHAR(45) DEFAULT "-",
FRAQUEZA_TIPO_TEXT0 VARCHAR(45) DEFAULT "-",
IMUNIDADE_TIPO_TEXT0 VARCHAR(45) DEFAULT "-",
RESISTENCIA_TIPO_TEXT0 VARCHAR(45) DEFAULT "-");











