USE pokedex;

CREATE TABLE pokemon_habilidade (
ID_POKEMON_HABILIDADE INT PRIMARY KEY AUTO_INCREMENT,
ID_FK_POKEMON_HAB INT,
ID_FK_HAB_POKEMON INT,
FOREIGN KEY (ID_FK_POKEMON_HAB) REFERENCES pokemon (ID_POKEMON),
FOREIGN KEY (ID_FK_HAB_POKEMON) REFERENCES habilidade (ID_HABILIDADE))
