USE pokedex;
CREATE TABLE MOVIMENTO (
ID_MOVIMENTO INT AUTO_INCREMENT PRIMARY KEY ,
NOME_MOVIMENTO VARCHAR(45) DEFAULT "-",
DESCRICAO_MOVIMENTO VARCHAR (200) DEFAULT "-",
PODER_MOVIMENTO INT DEFAULT 0,
PRECISAO_MOVIMENTO INT DEFAULT 0,
CATEGORIA_MOVIMENTO VARCHAR(45),
ID_FK_TIPO_MOVIMENTO INT,
ID_TIPO_MOVIEMNTO_TEXTO VARCHAR(45) DEFAULT "-",
FOREIGN KEY (ID_FK_TIPO_MOVIMENTO) REFERENCES TIPO (ID_TIPO))










