USE pokedex;

CREATE TABLE pokemon (
ID_POKEMON INT PRIMARY KEY,
NOME_POKEMON VARCHAR(45),
LINHA_EVOLUTIVA_POKEMON VARCHAR(200),
ALTURA_POKEMON FLOAT,
PESO_POKEMOPN FLOAT,
DESCRICAO_POKEMON VARCHAR(200),
NIVEL_EVOLUCAO INT,
ROTA_DE_ENCONTRO VARCHAR(200),
TIPO_PRIMARIO_POKEMON_TEXT VARCHAR(45),
TIPO_SECUNDARIO_POKEMON_TEXT VARCHAR(45),
HABILIDADE_POKEMON_TEXT VARCHAR(45),
ID_FK_TIPO_PRIMARIO INT,
ID_FK_TIPO_SECUNDARIO INT,
ID_FK_MOVIMENTOS INT,
ID_FK_HABILIDADES INT,
STATUS_GERAL_POKEMON INT,
STATUS_ATQ INT,
STATUS_DEF INT,
STATUS_HP INT,
FOREIGN KEY (ID_FK_TIPO_PRIMARIO) REFERENCES tipo (ID_TIPO),
FOREIGN KEY (ID_FK_TIPO_SECUNDARIO) REFERENCES tipo (ID_TIPO),
FOREIGN KEY (ID_FK_MOVIMENTOS) REFERENCES movimento (ID_MOVIMENTO),
FOREIGN KEY (ID_FK_HABILIDADES) REFERENCES habilidade (ID_HABILIDADE))





