use pokedex;
SELECT * FROM habilidade;

SHOW CREATE TABLE habilidade; -- comando para ver como foi criado a tabela "tipo", no caso as propriedades dos campos.

INSERT INTO habilidade (NOME_HABILIDADE, DESCRICAO_HABILIDADE)
VALUES 
('Clear Body', 'Impede que outros Pokémon diminuam seus stats.'),
('Blaze', 'Aumenta o poder dos movimentos do tipo Fogo em situações críticas.'),
('Overgrow', 'Aumenta o poder dos movimentos do tipo Grama em situações críticas.'),
('Torrent', 'Aumenta o poder dos movimentos do tipo Água em situações críticas.'),
('Vital Spirit', 'Impede que o Pokémon entre em sono.'),
('Color Change', 'Altera o tipo do Pokémon para o do movimento do oponente.'),
('Natural Cure', 'Todos os problemas de status: Queimadura, Paralisia, Sono, Congelamento, Veneno são curados quando o Pokémon é trocado.'),
('Filter', 'Reduz o dano de ataques super efetivos.'),
('Iron Cutter', ''),
('Levitate', 'Flutuando no ar, o Pokémon recebe imunidade total a todos os movimentos do tipo Terra.'),
('Flame Body', 'Contato com o Pokémon pode queimar o atacante.'),
('Intimidate', 'Diminui o Ataque do oponente.'),
('Tinted Lens', 'Aumenta o poder dos movimentos "não muito efetivos".'),
('Water Absorb', 'Restaura HP se atingido por um movimento do tipo Água.'),
('Rain Dish', 'O Pokémon gradualmente recupera HP na chuva.'),
('Swift Swim', 'Aumenta a Velocidade do Pokémon na chuva.'),
('Sticky Hold', 'Protege o Pokémon de roubo de itens.'),
('Sand Veil', 'Aumenta a evasão do Pokémon em uma tempestade de areia.'),
('Focus', 'Aumenta o poder dos movimentos mais fracos do Pokémon.'),
('Run Away', 'Permite uma fuga certa de Pokémon selvagens.'),
('Swarm', 'Aumenta o poder dos movimentos do tipo Inseto em situações críticas.'),
('Soundproof', 'Dá imunidade total a todos os movimentos baseados em som.'),
('East Fighting', ''),
('Keen Eye', 'Impede que outros Pokémon diminuam a precisão.'),
('Shed Skin', 'O Pokémon pode curar seus próprios problemas de status.'),
('Pressure', 'O Pokémon aumenta o uso de PP do oponente.'),
('Sand Veil', 'Aumenta a evasão do Pokémon em uma tempestade de areia.'),
('Spirit Guard', 'Aumenta a Defesa do Pokémon em uma tempestade de areia.'),
('Foul Play', ''),
('Hydration', 'Cura problemas de status se estiver chovendo.'),
('Focus', 'Aumenta o poder dos movimentos mais fracos do Pokémon.'),
('Hardened', ''),
('Inner Focus', 'O Pokémon não pode ser feito recuar.'),
('Gust', ''),
('Steely Spirit', ''),
('Psychic Power', ''),
('Magnet Pull', 'Impede que Pokémon do tipo Aço escapem.'),
('Rain Dish', 'O Pokémon gradualmente recupera HP na chuva.'),
('Levitate', 'Flutuando no ar, o Pokémon recebe imunidade total a todos os movimentos do tipo Terra.'),
('Voracious Heat', ''),
('Blackout', ''),
('East Attack', ''),
('Levitate', 'Flutuando no ar, o Pokémon recebe imunidade total a todos os movimentos do tipo Terra.'),
('Hardened', ''),
('Pressure', 'O Pokémon aumenta o uso de PP do oponente.'),
('Intimidate', 'Diminui o Ataque do oponente.'),
('Natural Cure', 'Todos os problemas de status: Queimadura, Paralisia, Sono, Congelamento, Veneno são curados quando o Pokémon é trocado.'),
('Insomnia', 'Impede que o Pokémon entre em sono.'),
('Hardened', ''),
('Steely Spirit', ''),
('Intimidate', 'Diminui o Ataque do oponente.'),
('Hardened', ''),
('Flame Body', 'Contato com o Pokémon pode queimar o atacante.'),
('Water Body', 'Restaura HP se atingido por um movimento do tipo Água.'),
('Magnet Pull', 'Impede que Pokémon do tipo Aço escapem.'),
('Overgrow', 'Aumenta o poder dos movimentos do tipo Grama em situações críticas.'),
('Swift Swim', 'Aumenta a Velocidade do Pokémon na chuva.'),
('Blackout', ''),
('Ice Body', 'O Pokémon gradualmente recupera HP em uma tempestade de granizo.'),
('Natural Cure', 'Todos os problemas de status: Queimadura, Paralisia, Sono, Congelamento, Veneno são curados quando o Pokémon é trocado.'),
('Filter', 'Reduz o dano de ataques super efetivos.'),
('Natural Cure', 'Todos os problemas de status: Queimadura, Paralisia, Sono, Congelamento, Veneno são curados quando o Pokémon é trocado.'),
('Hardened', ''),
('Water Body', 'Restaura HP se atingido por um movimento do tipo Água.'),
('Overgrow', 'Aumenta o poder dos movimentos do tipo Grama em situações críticas.'),
('Spirit Guard', 'Aumenta a Defesa do Pokémon em uma tempestade de areia.'),
('Hardened', ''),
('Magnet Pull', 'Impede que Pokémon do tipo Aço escapem.'),
('Iron Skin', ''),
('Sand Skin', ''),
('Pressure', 'O Pokémon aumenta o uso de PP do oponente.'),
('Run Away', 'Permite uma fuga certa de Pokémon selvagens.'),
('Deep Sleep', 'Impede que o Pokémon entre em sono.'),
('Natural Cure', 'Todos os problemas de status: Queimadura, Paralisia, Sono, Congelamento, Veneno são curados quando o Pokémon é trocado.'),
('Pressure', 'O Pokémon aumenta o uso de PP do oponente.'),
('Flame Body', 'Contato com o Pokémon pode queimar o atacante.');

